// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.tutorial1;

public final class CustomerProtos {
  private CustomerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string CustomerId = 1;
    /**
     * <code>required string CustomerId = 1;</code>
     */
    boolean hasCustomerId();
    /**
     * <code>required string CustomerId = 1;</code>
     */
    java.lang.String getCustomerId();
    /**
     * <code>required string CustomerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    // required string Name = 2;
    /**
     * <code>required string Name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string Name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string Name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 MaximumOrderAmount = 3;
    /**
     * <code>required int32 MaximumOrderAmount = 3;</code>
     */
    boolean hasMaximumOrderAmount();
    /**
     * <code>required int32 MaximumOrderAmount = 3;</code>
     */
    int getMaximumOrderAmount();

    // repeated .tutorial.Customer.Contact contacts = 4;
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    java.util.List<com.example.tutorial1.CustomerProtos.Customer.Contact> 
        getContactsList();
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    com.example.tutorial1.CustomerProtos.Customer.Contact getContacts(int index);
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    int getContactsCount();
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    java.util.List<? extends com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder> 
        getContactsOrBuilderList();
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder getContactsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.Customer}
   */
  public static final class Customer extends
      com.google.protobuf.GeneratedMessage
      implements CustomerOrBuilder {
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Customer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Customer defaultInstance;
    public static Customer getDefaultInstance() {
      return defaultInstance;
    }

    public Customer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              customerId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              maximumOrderAmount_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                contacts_ = new java.util.ArrayList<com.example.tutorial1.CustomerProtos.Customer.Contact>();
                mutable_bitField0_ |= 0x00000008;
              }
              contacts_.add(input.readMessage(com.example.tutorial1.CustomerProtos.Customer.Contact.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          contacts_ = java.util.Collections.unmodifiableList(contacts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial1.CustomerProtos.Customer.class, com.example.tutorial1.CustomerProtos.Customer.Builder.class);
    }

    public static com.google.protobuf.Parser<Customer> PARSER =
        new com.google.protobuf.AbstractParser<Customer>() {
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    public interface ContactOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string Name = 1;
      /**
       * <code>required string Name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string Name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string Name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // optional string ContactDetails = 2;
      /**
       * <code>optional string ContactDetails = 2;</code>
       */
      boolean hasContactDetails();
      /**
       * <code>optional string ContactDetails = 2;</code>
       */
      java.lang.String getContactDetails();
      /**
       * <code>optional string ContactDetails = 2;</code>
       */
      com.google.protobuf.ByteString
          getContactDetailsBytes();
    }
    /**
     * Protobuf type {@code tutorial.Customer.Contact}
     */
    public static final class Contact extends
        com.google.protobuf.GeneratedMessage
        implements ContactOrBuilder {
      // Use Contact.newBuilder() to construct.
      private Contact(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Contact(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Contact defaultInstance;
      public static Contact getDefaultInstance() {
        return defaultInstance;
      }

      public Contact getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Contact(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                contactDetails_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_Contact_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.tutorial1.CustomerProtos.Customer.Contact.class, com.example.tutorial1.CustomerProtos.Customer.Contact.Builder.class);
      }

      public static com.google.protobuf.Parser<Contact> PARSER =
          new com.google.protobuf.AbstractParser<Contact>() {
        public Contact parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Contact(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Contact> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string Name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string Name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string Name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string ContactDetails = 2;
      public static final int CONTACTDETAILS_FIELD_NUMBER = 2;
      private java.lang.Object contactDetails_;
      /**
       * <code>optional string ContactDetails = 2;</code>
       */
      public boolean hasContactDetails() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string ContactDetails = 2;</code>
       */
      public java.lang.String getContactDetails() {
        java.lang.Object ref = contactDetails_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contactDetails_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ContactDetails = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContactDetailsBytes() {
        java.lang.Object ref = contactDetails_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactDetails_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        name_ = "";
        contactDetails_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getContactDetailsBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getContactDetailsBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.tutorial1.CustomerProtos.Customer.Contact parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.example.tutorial1.CustomerProtos.Customer.Contact prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tutorial.Customer.Contact}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_Contact_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_Contact_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.example.tutorial1.CustomerProtos.Customer.Contact.class, com.example.tutorial1.CustomerProtos.Customer.Contact.Builder.class);
        }

        // Construct using com.example.tutorial1.CustomerProtos.Customer.Contact.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          contactDetails_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_Contact_descriptor;
        }

        public com.example.tutorial1.CustomerProtos.Customer.Contact getDefaultInstanceForType() {
          return com.example.tutorial1.CustomerProtos.Customer.Contact.getDefaultInstance();
        }

        public com.example.tutorial1.CustomerProtos.Customer.Contact build() {
          com.example.tutorial1.CustomerProtos.Customer.Contact result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.example.tutorial1.CustomerProtos.Customer.Contact buildPartial() {
          com.example.tutorial1.CustomerProtos.Customer.Contact result = new com.example.tutorial1.CustomerProtos.Customer.Contact(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.contactDetails_ = contactDetails_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.example.tutorial1.CustomerProtos.Customer.Contact) {
            return mergeFrom((com.example.tutorial1.CustomerProtos.Customer.Contact)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.example.tutorial1.CustomerProtos.Customer.Contact other) {
          if (other == com.example.tutorial1.CustomerProtos.Customer.Contact.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasContactDetails()) {
            bitField0_ |= 0x00000002;
            contactDetails_ = other.contactDetails_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.tutorial1.CustomerProtos.Customer.Contact parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.tutorial1.CustomerProtos.Customer.Contact) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string Name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string Name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string Name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string Name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string Name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string Name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string Name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // optional string ContactDetails = 2;
        private java.lang.Object contactDetails_ = "";
        /**
         * <code>optional string ContactDetails = 2;</code>
         */
        public boolean hasContactDetails() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string ContactDetails = 2;</code>
         */
        public java.lang.String getContactDetails() {
          java.lang.Object ref = contactDetails_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            contactDetails_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string ContactDetails = 2;</code>
         */
        public com.google.protobuf.ByteString
            getContactDetailsBytes() {
          java.lang.Object ref = contactDetails_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            contactDetails_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ContactDetails = 2;</code>
         */
        public Builder setContactDetails(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          contactDetails_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ContactDetails = 2;</code>
         */
        public Builder clearContactDetails() {
          bitField0_ = (bitField0_ & ~0x00000002);
          contactDetails_ = getDefaultInstance().getContactDetails();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ContactDetails = 2;</code>
         */
        public Builder setContactDetailsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          contactDetails_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tutorial.Customer.Contact)
      }

      static {
        defaultInstance = new Contact(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:tutorial.Customer.Contact)
    }

    private int bitField0_;
    // required string CustomerId = 1;
    public static final int CUSTOMERID_FIELD_NUMBER = 1;
    private java.lang.Object customerId_;
    /**
     * <code>required string CustomerId = 1;</code>
     */
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string CustomerId = 1;</code>
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string CustomerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string Name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string Name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 MaximumOrderAmount = 3;
    public static final int MAXIMUMORDERAMOUNT_FIELD_NUMBER = 3;
    private int maximumOrderAmount_;
    /**
     * <code>required int32 MaximumOrderAmount = 3;</code>
     */
    public boolean hasMaximumOrderAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 MaximumOrderAmount = 3;</code>
     */
    public int getMaximumOrderAmount() {
      return maximumOrderAmount_;
    }

    // repeated .tutorial.Customer.Contact contacts = 4;
    public static final int CONTACTS_FIELD_NUMBER = 4;
    private java.util.List<com.example.tutorial1.CustomerProtos.Customer.Contact> contacts_;
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    public java.util.List<com.example.tutorial1.CustomerProtos.Customer.Contact> getContactsList() {
      return contacts_;
    }
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    public java.util.List<? extends com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder> 
        getContactsOrBuilderList() {
      return contacts_;
    }
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    public int getContactsCount() {
      return contacts_.size();
    }
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    public com.example.tutorial1.CustomerProtos.Customer.Contact getContacts(int index) {
      return contacts_.get(index);
    }
    /**
     * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
     */
    public com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder getContactsOrBuilder(
        int index) {
      return contacts_.get(index);
    }

    private void initFields() {
      customerId_ = "";
      name_ = "";
      maximumOrderAmount_ = 0;
      contacts_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCustomerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaximumOrderAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getContactsCount(); i++) {
        if (!getContacts(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCustomerIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, maximumOrderAmount_);
      }
      for (int i = 0; i < contacts_.size(); i++) {
        output.writeMessage(4, contacts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCustomerIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maximumOrderAmount_);
      }
      for (int i = 0; i < contacts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, contacts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.tutorial1.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial1.CustomerProtos.Customer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial1.CustomerProtos.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.tutorial1.CustomerProtos.Customer.class, com.example.tutorial1.CustomerProtos.Customer.Builder.class);
      }

      // Construct using com.example.tutorial1.CustomerProtos.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContactsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        customerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        maximumOrderAmount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial1.CustomerProtos.internal_static_tutorial_Customer_descriptor;
      }

      public com.example.tutorial1.CustomerProtos.Customer getDefaultInstanceForType() {
        return com.example.tutorial1.CustomerProtos.Customer.getDefaultInstance();
      }

      public com.example.tutorial1.CustomerProtos.Customer build() {
        com.example.tutorial1.CustomerProtos.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.tutorial1.CustomerProtos.Customer buildPartial() {
        com.example.tutorial1.CustomerProtos.Customer result = new com.example.tutorial1.CustomerProtos.Customer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.customerId_ = customerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maximumOrderAmount_ = maximumOrderAmount_;
        if (contactsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            contacts_ = java.util.Collections.unmodifiableList(contacts_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.contacts_ = contacts_;
        } else {
          result.contacts_ = contactsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial1.CustomerProtos.Customer) {
          return mergeFrom((com.example.tutorial1.CustomerProtos.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.tutorial1.CustomerProtos.Customer other) {
        if (other == com.example.tutorial1.CustomerProtos.Customer.getDefaultInstance()) return this;
        if (other.hasCustomerId()) {
          bitField0_ |= 0x00000001;
          customerId_ = other.customerId_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMaximumOrderAmount()) {
          setMaximumOrderAmount(other.getMaximumOrderAmount());
        }
        if (contactsBuilder_ == null) {
          if (!other.contacts_.isEmpty()) {
            if (contacts_.isEmpty()) {
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureContactsIsMutable();
              contacts_.addAll(other.contacts_);
            }
            onChanged();
          }
        } else {
          if (!other.contacts_.isEmpty()) {
            if (contactsBuilder_.isEmpty()) {
              contactsBuilder_.dispose();
              contactsBuilder_ = null;
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000008);
              contactsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContactsFieldBuilder() : null;
            } else {
              contactsBuilder_.addAllMessages(other.contacts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCustomerId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasMaximumOrderAmount()) {
          
          return false;
        }
        for (int i = 0; i < getContactsCount(); i++) {
          if (!getContacts(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.tutorial1.CustomerProtos.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.tutorial1.CustomerProtos.Customer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string CustomerId = 1;
      private java.lang.Object customerId_ = "";
      /**
       * <code>required string CustomerId = 1;</code>
       */
      public boolean hasCustomerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string CustomerId = 1;</code>
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string CustomerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string CustomerId = 1;</code>
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string CustomerId = 1;</code>
       */
      public Builder clearCustomerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>required string CustomerId = 1;</code>
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        customerId_ = value;
        onChanged();
        return this;
      }

      // required string Name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string Name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string Name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string Name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 MaximumOrderAmount = 3;
      private int maximumOrderAmount_ ;
      /**
       * <code>required int32 MaximumOrderAmount = 3;</code>
       */
      public boolean hasMaximumOrderAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 MaximumOrderAmount = 3;</code>
       */
      public int getMaximumOrderAmount() {
        return maximumOrderAmount_;
      }
      /**
       * <code>required int32 MaximumOrderAmount = 3;</code>
       */
      public Builder setMaximumOrderAmount(int value) {
        bitField0_ |= 0x00000004;
        maximumOrderAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 MaximumOrderAmount = 3;</code>
       */
      public Builder clearMaximumOrderAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maximumOrderAmount_ = 0;
        onChanged();
        return this;
      }

      // repeated .tutorial.Customer.Contact contacts = 4;
      private java.util.List<com.example.tutorial1.CustomerProtos.Customer.Contact> contacts_ =
        java.util.Collections.emptyList();
      private void ensureContactsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          contacts_ = new java.util.ArrayList<com.example.tutorial1.CustomerProtos.Customer.Contact>(contacts_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial1.CustomerProtos.Customer.Contact, com.example.tutorial1.CustomerProtos.Customer.Contact.Builder, com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder> contactsBuilder_;

      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public java.util.List<com.example.tutorial1.CustomerProtos.Customer.Contact> getContactsList() {
        if (contactsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contacts_);
        } else {
          return contactsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public int getContactsCount() {
        if (contactsBuilder_ == null) {
          return contacts_.size();
        } else {
          return contactsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public com.example.tutorial1.CustomerProtos.Customer.Contact getContacts(int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);
        } else {
          return contactsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder setContacts(
          int index, com.example.tutorial1.CustomerProtos.Customer.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.set(index, value);
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder setContacts(
          int index, com.example.tutorial1.CustomerProtos.Customer.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder addContacts(com.example.tutorial1.CustomerProtos.Customer.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder addContacts(
          int index, com.example.tutorial1.CustomerProtos.Customer.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(index, value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder addContacts(
          com.example.tutorial1.CustomerProtos.Customer.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder addContacts(
          int index, com.example.tutorial1.CustomerProtos.Customer.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder addAllContacts(
          java.lang.Iterable<? extends com.example.tutorial1.CustomerProtos.Customer.Contact> values) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          super.addAll(values, contacts_);
          onChanged();
        } else {
          contactsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder clearContacts() {
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public Builder removeContacts(int index) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.remove(index);
          onChanged();
        } else {
          contactsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public com.example.tutorial1.CustomerProtos.Customer.Contact.Builder getContactsBuilder(
          int index) {
        return getContactsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder getContactsOrBuilder(
          int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);  } else {
          return contactsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public java.util.List<? extends com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder> 
           getContactsOrBuilderList() {
        if (contactsBuilder_ != null) {
          return contactsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contacts_);
        }
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public com.example.tutorial1.CustomerProtos.Customer.Contact.Builder addContactsBuilder() {
        return getContactsFieldBuilder().addBuilder(
            com.example.tutorial1.CustomerProtos.Customer.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public com.example.tutorial1.CustomerProtos.Customer.Contact.Builder addContactsBuilder(
          int index) {
        return getContactsFieldBuilder().addBuilder(
            index, com.example.tutorial1.CustomerProtos.Customer.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Customer.Contact contacts = 4;</code>
       */
      public java.util.List<com.example.tutorial1.CustomerProtos.Customer.Contact.Builder> 
           getContactsBuilderList() {
        return getContactsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial1.CustomerProtos.Customer.Contact, com.example.tutorial1.CustomerProtos.Customer.Contact.Builder, com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder> 
          getContactsFieldBuilder() {
        if (contactsBuilder_ == null) {
          contactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.tutorial1.CustomerProtos.Customer.Contact, com.example.tutorial1.CustomerProtos.Customer.Contact.Builder, com.example.tutorial1.CustomerProtos.Customer.ContactOrBuilder>(
                  contacts_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          contacts_ = null;
        }
        return contactsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Customer)
    }

    static {
      defaultInstance = new Customer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Customer)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Customer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Customer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Customer_Contact_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Customer_Contact_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\010tutorial\"\247\001\n\010Customer\022" +
      "\022\n\nCustomerId\030\001 \002(\t\022\014\n\004Name\030\002 \002(\t\022\032\n\022Max" +
      "imumOrderAmount\030\003 \002(\005\022,\n\010contacts\030\004 \003(\0132" +
      "\032.tutorial.Customer.Contact\032/\n\007Contact\022\014" +
      "\n\004Name\030\001 \002(\t\022\026\n\016ContactDetails\030\002 \001(\tB\'\n\025" +
      "com.example.tutorial1B\016CustomerProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Customer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Customer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Customer_descriptor,
              new java.lang.String[] { "CustomerId", "Name", "MaximumOrderAmount", "Contacts", });
          internal_static_tutorial_Customer_Contact_descriptor =
            internal_static_tutorial_Customer_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_Customer_Contact_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Customer_Contact_descriptor,
              new java.lang.String[] { "Name", "ContactDetails", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
